language: python

python:
    - "3.5"

sudo: false

env:
    - TOX_ENV=py35-d109
    - TOX_ENV=py35-d110

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-djangomaster
      - env: TOX_ENV=py34-djangomaster
      - env: TOX_ENV=py35-djangomaster

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
