language: python

python:
    - "3.6"

sudo: false

env:
    - TOX_ENV=py36-plain
    - TOX_ENV=py36-sqla
    - TOX_ENV=py36-d109
    - TOX_ENV=py36-d110

matrix:
    fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
