language: python

python:
    - "3.5"

sudo: false

env:
    - TOX_ENV=py35-plain
    - TOX_ENV=py35-d109
    - TOX_ENV=py35-d110

matrix:
    fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
