# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_event_aggregate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
